/* Individual payments; amounts are stored as integer kopecks. */
let paymentRevision=0, paymentPayload={}, savingPayment=false, verifiedAdmin=false;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const rub=n=>(n/100).toLocaleString('ru-RU',{minimumFractionDigits:0,maximumFractionDigits:2})+' ₽';
function emptyAccount(){return {cost:null,stages:Array.from({length:3},()=>({amount:0,date:''}))}}
function accountOf(p){return p?.payment||emptyAccount()}
function paymentStatus(p){const a=accountOf(p),total=a.stages.reduce((s,x)=>s+x.amount,0);if(!p.payment&&p.paid)return 'Оплачено ранее';if(a.cost===null)return total?'Частично · стоимость не задана':'Стоимость не задана';if(total>a.cost)return 'Переплата';if(total===a.cost)return 'Оплачено';return total?'Частично':'Не оплачено'}
function paymentSummary(p){const a=accountOf(p),sum=a.stages.reduce((s,x)=>s+x.amount,0);return `Стоимость: ${a.cost===null?'не задана':rub(a.cost)} · Внесено: ${rub(sum)}${a.cost===null?'':sum>a.cost?' · Переплата: '+rub(sum-a.cost):' · Осталось: '+rub(a.cost-sum)}`}
function moneyInput(v,optional=false){const s=String(v).trim().replace(/\s/g,'').replace(',','.');if(!s&&optional)return null;if(!s)return 0;if(!/^\d+(\.\d{1,2})?$/.test(s))throw Error('Введите неотрицательную сумму, не более двух знаков после запятой.');const [r,k='']=s.split('.');const n=Number(r)*100+Number(k.padEnd(2,'0'));if(!Number.isSafeInteger(n)||n>10000000000)throw Error('Слишком большая сумма.');return n}
function accountFields(p){const a=accountOf(p);return `<div class="payment-account"><div class="field"><label>Стоимость участия, ₽ (индивидуальная)</label><input class="payment-cost" inputmode="decimal" placeholder="Не задана" value="${a.cost===null?'':a.cost/100}" aria-label="Стоимость участия"></div>${!p.payment&&p.paid?'<div class="note">Ранее отмечено «Оплачено». Сумма неизвестна; внесите фактические платежи.</div>':''}${a.stages.map((x,i)=>`<div class="payment-stage"><b>Этап ${i+1}</b><div class="payment-inputs"><label>Внесено, ₽<input class="payment-amount" inputmode="decimal" value="${x.amount?x.amount/100:''}" placeholder="0" aria-label="Этап ${i+1}: сумма"></label><label>Дата платежа<input class="payment-date" type="date" value="${esc(x.date)}" aria-label="Этап ${i+1}: дата"></label></div></div>`).join('')}<div class="note payment-total">${esc(paymentSummary(p))}</div></div>`}
function readAccount(root){const cost=moneyInput(root.querySelector('.payment-cost').value,true),amounts=[...root.querySelectorAll('.payment-amount')],dates=[...root.querySelectorAll('.payment-date')];const stages=amounts.map((x,i)=>{const amount=moneyInput(x.value),date=dates[i].value;if(amount&&!date)throw Error('Укажите дату каждого внесённого платежа.');if(!amount&&date)throw Error('Укажите сумму платежа или очистите его дату.');return {amount,date}});return {cost,stages}}
function updatePaymentTotals(event){const root=event.target.closest('.payment-account');if(!root)return;try{root.querySelector('.payment-total').textContent=paymentSummary({payment:readAccount(root)})}catch(e){root.querySelector('.payment-total').textContent=e.message}}
function preserveAccount(root,p){const a=readAccount(root);if(!p.payment&&a.cost===null&&a.stages.every(x=>!x.amount&&!x.date))return {...p};return {...p,payment:a,paid:a.cost!==null&&a.stages.reduce((s,x)=>s+x.amount,0)>=a.cost}}
function syncRoleFields(){const companion=document.getElementById('roleInput').value==='companion';document.getElementById('guestFields').style.display=companion?'none':'block';document.querySelector('#modal .mini').style.display=companion?'none':'inline-block'}
function openEditor(c,i){if(!admin||!verifiedAdmin||!serverReady)return alert('Редактирование доступно администратору после загрузки общей базы.');editing=c!=null?{c,i}:null;const p=editing?data[c][i]:{name:'',guests:[],paid:false,role:'student'};document.getElementById('editorTitle').textContent=editing?'Участник и платежи':'Новый участник';document.getElementById('classInput').value=c||'11А';document.getElementById('nameInput').value=p.name||'';document.getElementById('roleInput').value=isCompanion(p)?'companion':'student';document.getElementById('paymentField').innerHTML='<h4>Личная оплата участника</h4>'+accountFields(p);document.getElementById('guestFields').innerHTML='';(p.guests||[]).forEach((g,i)=>addGuestField(g,p.guestPayments?.[i]||{}));document.getElementById('deleteBtn').style.display=editing?'block':'none';syncRoleFields();document.getElementById('modal').classList.add('open')}
function addGuestField(v='',old={}){const d=document.createElement('div');d.className='guestline payment-guest';d.paymentRecord=old;d.innerHTML=`<div class="guest-heading"><input class="guest-name" placeholder="Например: мама, папа" aria-label="Имя сопровождающего" value="${esc(v)}"><button type="button" onclick="if(confirm('Удалить гостя вместе с его платежами?'))this.closest('.payment-guest').remove()">×</button></div><details><summary>Индивидуальная стоимость и 3 платежа</summary>${accountFields(old)}</details>`;document.getElementById('guestFields').appendChild(d)}
async function saveEditor(){if(savingPayment||!verifiedAdmin)return;const c=document.getElementById('classInput').value,n=document.getElementById('nameInput').value.trim(),role=document.getElementById('roleInput').value;if(!n)return alert('Введите имя');const snapshot=JSON.stringify(data);try{const old=editing?data[editing.c][editing.i]:{};let p=preserveAccount(document.querySelector('#paymentField .payment-account'),old);const rows=[...document.querySelectorAll('.payment-guest')];if(role==='companion'&&rows.length)throw Error('Сначала удалите вложенных гостей или оставьте роль «Выпускник».');const guests=[],guestPayments=[];for(const row of rows){const name=row.querySelector('.guest-name').value.trim();if(!name)throw Error('Укажите имя каждого сопровождающего или удалите пустую строку.');guests.push(name);guestPayments.push(preserveAccount(row.querySelector('.payment-account'),row.paymentRecord||{}))}p={...p,name:n,role,guests,guestPayments};savingPayment=true;setPaymentBusy(true);if(editing){data[editing.c].splice(editing.i,1);if(editing.c===c)data[c].splice(editing.i,0,p);else data[c].push(p)}else data[c].push(p);await saveData();closeEditor();render()}catch(e){data=JSON.parse(snapshot);render();alert('Не удалось сохранить: '+e.message)}finally{savingPayment=false;setPaymentBusy(false)}}
function setPaymentBusy(b){document.querySelectorAll('#modal button,#modal input,#modal select').forEach(x=>x.disabled=b)}
const baseRender=render;
render=function(){baseRender();let h='';for(const c of ['11А','11Б','11В']){h+=`<h3 class="classTitle">${c}</h3>`;for(const [i,p] of data[c].entries()){const people=[{p,label:p.name},...(p.guests||[]).map((g,j)=>({p:p.guestPayments?.[j]||{},label:g+' — семья '+p.name}))];for(const person of people){const status=paymentStatus(person.p);h+=`<div class="row"><div class="grow"><b>${esc(person.label)}</b><small>${esc(status)}</small><small>${esc(paymentSummary(person.p))}</small>${accountOf(person.p).stages.map((s,j)=>s.amount?`<small>Этап ${j+1}: ${rub(s.amount)} · ${esc(s.date.split('-').reverse().join('.'))}</small>`:'').join('')}</div>${admin&&verifiedAdmin?`<button class="editbtn" onclick="openEditor('${c}',${i})">Изменить</button>`:''}</div>`}}}document.getElementById('paylist').innerHTML=h;const entries=[...document.querySelectorAll('#people .row')];let pos=0;for(const c of ['11А','11Б','11В'])for(const p of data[c]){const row=entries[pos++],badge=row?.querySelector('.badge');if(badge&&!isCompanion(p)){badge.textContent=paymentStatus(p);badge.classList.toggle('paid',paymentStatus(p)==='Оплачено');}}};
async function saveData(){if(!tg?.initData||!verifiedAdmin)throw Error('Откройте приложение в Telegram под аккаунтом администратора.');if(!serverReady)throw Error('Общая база ещё не загружена. Закройте и заново откройте приложение.');const payload={...paymentPayload,classes:data,expenses:expenses,rosterVersion:3,paymentSchemaVersion:1,_revision:paymentRevision};const r=await fetch('/api/data',{method:'POST',headers:{'content-type':'application/json','x-telegram-init-data':tg.initData},body:JSON.stringify(payload)});const j=await r.json();if(!r.ok||!j.ok)throw Error(r.status===409?'Данные уже изменены другим администратором. Заново откройте приложение и повторите ввод.':j.error||'Ошибка сохранения');paymentRevision=j.revision;paymentPayload={...payload,_revision:paymentRevision};serverReady=true}
async function loadServer(){serverReady=false;try{const r=await fetch('/api/data',{cache:'no-store'});if(!r.ok)throw Error();const j=await r.json();if(!j.ok)throw Error();paymentPayload=j.data||{};paymentRevision=paymentPayload._revision||0;if(j.data?.classes){data=j.data.classes;for(const c of ['11А','11Б','11В'])data[c]=(data[c]||[]).map(x=>({...x,role:isCompanion(x)?'companion':'student'}));if(Array.isArray(j.data.expenses))expenses=j.data.expenses.map(x=>typeof x==='string'?{name:x,amount:0}:{...x});expenseNames=expenses.map(x=>x.name)}serverReady=true;render()}catch(e){document.getElementById('paylist').textContent='Не удалось загрузить общую базу. Откройте приложение заново.'}}
async function startSession(){if(!tg?.initData)return;try{const r=await fetch('/api/session',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({initData:tg.initData})});const j=await r.json();verifiedAdmin=!!(r.ok&&j.ok&&j.isAdmin);admin=verifiedAdmin;if(admin)document.getElementById('adminWho').textContent=j.user?.username?'@'+j.user.username:'Администратор';render()}catch(e){verifiedAdmin=false;admin=false}}
function enterAdmin(){if(!verifiedAdmin)return alert('Редактирование доступно только администратору в Telegram.');admin=true;render();showPage('participants')}
const oldBuildReport=buildReport;
buildReport=function(){if(reportType==='summary')return oldBuildReport();let out='Выпускной 2027 — отчёт по участникам и оплате\n';for(const c of reportType==='class'?[reportClass]:['11А','11Б','11В']){out+='\n'+c+'\n';for(const p of data[c]){out+=p.name+' — '+paymentStatus(p)+'; '+paymentSummary(p)+'\n';(p.guests||[]).forEach((g,i)=>{const a=p.guestPayments?.[i]||{};out+='  '+g+' — '+paymentStatus(a)+'; '+paymentSummary(a)+'\n'})}}return out};
document.getElementById('modal').addEventListener('input',updatePaymentTotals);
